Add callbacks to EMFReader for GUI
DouglasHalse/spook-station pull request #8
Opened 2023-08-02 23:58 UTC by DouglasHalse

2023-08-10 17:21 UTC, Raisaur commented on SpookStationGui/main.py
> +    def setUseSoundActive(self, useSound, *largs):
_**S**_etUseSoundActive

2023-08-10 17:22 UTC, Raisaur commented on SpookStationGui/main.py
> +    def onMuteButtonChange(self):
**O**nMuteButtonChange

2023-08-10 17:22 UTC, Raisaur requested changes
See comments

2023-08-11 21:44 UTC, Raisaur approved these changes
yes

2023-08-11 21:44 UTC, merged

2023-08-11 21:52 UTC, DouglasHalse commented
Oh lord, I wanted to squash those commits before finishing this